- use macos-12 image and java 11 in GH actions - reorder/reworked steps for Android and iOS configurations in ADO

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -60,6 +60,56 @@ jobs:
         IOS_SIM_NAME: iPhone SE (3rd generation)
 
   steps:
+
+  - task: CmdLine@2
+    displayName: 'Configure and start Android emulator'
+    inputs:
+      script: |        
+        echo "Configuring Environment"
+        brew install --cask temurin@8
+        export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
+        export PATH=$JAVA_HOME/bin:$PATH
+        echo export "ANDROID_HOME=\$ANDROID_HOME" >> ~/.bash_profile
+        export PATH=$PATH:$ANDROID_HOME
+        
+        echo "ANDROID_HOME: ${ANDROID_HOME}"
+        echo "JAVA_HOME: ${JAVA_HOME}"
+        echo "PATH: ${PATH}"
+        
+        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "$(ANDROID_SDK_ID)"
+        echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n "$(ANDROID_EMU_NAME)" -k "$(ANDROID_SDK_ID)" -f
+        $ANDROID_HOME/emulator/emulator -list-avds
+
+        echo "Starting emulator"
+        nohup $ANDROID_HOME/emulator/emulator -avd "$(ANDROID_EMU_NAME)" -gpu swiftshader_indirect -noaudio -no-boot-anim -no-snapshot -verbose > /dev/null 2>&1 &
+        $ANDROID_HOME/platform-tools/adb wait-for-device
+        for i in {1..300}; do
+            $ANDROID_HOME/platform-tools/adb shell pm list packages >/dev/null 2>&1 && break
+            sleep 2
+        done
+        if [[ $i -eq 300 ]]; then
+          echo "Emulator failed to boot in time" >&2
+          exit 1
+        fi
+        $ANDROID_HOME/platform-tools/adb devices
+        echo "Emulator started"
+    condition: and(succeeded(), eq(variables['PLATFORM_NAME'], 'android'))
+
+  - task: CmdLine@2
+    displayName: 'Start iOS simulator'
+    inputs:
+      script: |
+        echo "Starting ${IOS_SIM_ID} simulator"
+        npm install -g ios-sim@9.0.0
+        ios-sim showdevicetypes
+        ios-sim start --devicetypeid "$(IOS_SIM_ID)"
+        echo "Simulator started"
+
+        echo "Wait for simulator to be ready"
+        SIM_UID="$(xcrun simctl list devices | grep -m 1 "$IOS_SIM_NAME" | grep -E -o -i "([0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12})")"
+        xcrun simctl bootstatus $SIM_UID
+    condition: and(succeeded(), eq(variables['PLATFORM_NAME'], 'ios'))
+
   - task: CmdLine@2
     displayName: 'Configure Appium'
     inputs:
@@ -91,67 +141,24 @@ jobs:
         echo "Appium doctor installed and executed"
 
   - task: CmdLine@2
-    displayName: 'Configure UIA2 driver and start Android emulator'
-    inputs:
-      script: |
-        echo "Installing UIA2 driver"
-        appium driver install uiautomator2
-        appium driver list
-        echo "UIA2 driver installed"
-        
-        echo "Configuring Environment"
-        brew install --cask temurin@8
-        export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
-        export PATH=$JAVA_HOME/bin:$PATH
-        echo export "ANDROID_HOME=\$ANDROID_HOME" >> ~/.bash_profile
-        export PATH=$PATH:$ANDROID_HOME
-        
-        echo "ANDROID_HOME: ${ANDROID_HOME}"
-        echo "JAVA_HOME: ${JAVA_HOME}"
-        echo "PATH: ${PATH}"
-        
-        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "$(ANDROID_SDK_ID)"
-        echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n "$(ANDROID_EMU_NAME)" -k "$(ANDROID_SDK_ID)" -f
-        $ANDROID_HOME/emulator/emulator -list-avds
-
-        echo "Starting emulator"
-        nohup $ANDROID_HOME/emulator/emulator -avd "$(ANDROID_EMU_NAME)" -gpu swiftshader_indirect -noaudio -no-boot-anim -no-snapshot -verbose > /dev/null 2>&1 &
-        $ANDROID_HOME/platform-tools/adb wait-for-device
-        booted=false
-        for i in {1..300}; do
-            if $ANDROID_HOME/platform-tools/adb shell pm list packages >/dev/null 2>&1; then
-                booted=true
-                break
-            fi
-            sleep 2
-        done
-        if [[ "$booted" != true ]]; then
-          echo "Emulator failed to boot in time" >&2
-          exit 1
-        fi
-        $ANDROID_HOME/platform-tools/adb devices
-        echo "Emulator started"
-    condition: and(succeeded(), eq(variables['PLATFORM_NAME'], 'android'))
-
-  - task: CmdLine@2
-    displayName: 'Configure XCUITest driver and start iOS simulator'
+    displayName: 'Configure XCUITest driver'
     inputs:
       script: |
         echo "Installing XCUITest driver"
         appium driver install xcuitest
         appium driver list
         echo "XCUITest driver installed"
-
-        echo "Starting ${IOS_SIM_ID} simulator"
-        npm install -g ios-sim@9.0.0
-        ios-sim showdevicetypes
-        ios-sim start --devicetypeid "$(IOS_SIM_ID)"
-        echo "Simulator started"
-
-        echo "Wait for simulator to be ready"
-        SIM_UID="$(xcrun simctl list devices | grep -m 1 "$IOS_SIM_NAME" | grep -E -o -i "([0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12})")"
-        xcrun simctl bootstatus $SIM_UID
     condition: and(succeeded(), eq(variables['PLATFORM_NAME'], 'ios'))
+
+  - task: CmdLine@2
+    displayName: 'Configure UIA2 driver'
+    inputs:
+      script: |
+        echo "Installing UIA2 driver"
+        appium driver install uiautomator2
+        appium driver list
+        echo "UIA2 driver installed"
+    condition: and(succeeded(), eq(variables['PLATFORM_NAME'], 'android'))
 
   - task: CmdLine@2
     displayName: 'Start Appium server'
